CREATE TABLE TB_TURNO_FIXO (
    ID NUMBER(8) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    TRABALHA_NO_FERIADO NUMBER(1), -- 0 => FALSE || 1 => TRUE
    DOMINGO NUMBER(1),
    SEGUNDA NUMBER(1),
    TERCA NUMBER(1),
    QUARTA NUMBER(1),
    QUINTA NUMBER(1),
    SEXTA NUMBER(1),
    SABADO NUMBER(1),
    CONSTRAINT TURNO_FIXO_PK PRIMARY KEY (ID)
);
