CREATE TABLE TB_FERIADO (
       ID NUMBER(8) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
       NOME VARCHAR(125) NOT NULL,
       DATA DATE NOT NULL,
       TIPO VARCHAR(8) NOT NULL,
       DIA_SEMANA VARCHAR(13) NOT NULL,
       CONSTRAINT FERIADO_PK PRIMARY KEY (ID)
);
