CREATE TABLE TB_TURNO (
    ID NUMBER(8) GENERATED ALWAYS as IDENTITY(START WITH 1 INCREMENT BY 1),
    TURNO_FIXO_ID NUMBER(8) DEFAULT NULL,
    TURNO_ALTERNADO_ID NUMBER(8) DEFAULT NULL,
    NOME VARCHAR2(125) NOT NULL,
    SIGLA VARCHAR2(5) NOT NULL,
    TRABALHA_NO_FERIADO NUMBER(1) DEFAULT 0, -- 0 => False || 1 => True
    HORA_INICIO NUMBER(4, 2), -- Campos que recebem a hora no padrão 10.50 simbolizam 10:30h
    HORA_TERMINO NUMBER(4, 2),
    TOTAL_HORAS NUMBER(6, 2),
    CONSTRAINT TURNO_PK PRIMARY KEY (ID),
    CONSTRAINT FK_TURNO_FIXO FOREIGN KEY(TURNO_FIXO_ID) REFERENCES TB_TURNO_FIXO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_TURNO_ALTERNADO FOREIGN KEY(TURNO_ALTERNADO_ID) REFERENCES TB_TURNO_ALTERNADO(ID) ON DELETE CASCADE
);
