CREATE TABLE TB_LOG (
    ID NUMBER(8) GENERATED ALWAYS as IDENTITY(START WITH 1 INCREMENT BY 1),
    FUNCIONARIO_ID NUMBER(8) NOT NULL,
    DATA_ALTERACAO DATE NOT NULL,
    OPERACAO CHAR(2) NOT NULL,
    QUERY VARCHAR2(4000 CHAR)
);