CREATE TABLE TB_ESCALA_TRABALHO (
    ID NUMBER(8) GENERATED ALWAYS as IDENTITY(START WITH 1 INCREMENT BY 1),
    FUNCIONARIO_ID NUMBER(8) NOT NULL,
    DATA DATE NOT NULL,
    TOTAL_HORAS NUMBER(6,2),
    TOTAL_HORAS_EXTRAS NUMBER(6,2),
    QUANT_SABADOS_TRABALHADOS NUMBER(2),
    QUANT_DOMINGOS_TRABALHADOS NUMBER(2),
    QUANT_FERIADOS_TRABALHADOS NUMBER(2),
    CONSTRAINT ESCALA_TRABALHO_PK PRIMARY KEY (ID),
    CONSTRAINT FK_FUNCIONARIO FOREIGN KEY(FUNCIONARIO_ID) REFERENCES TB_FUNCIONARIO(ID)
);