CREATE TABLE TB_ESCALA_TIPO (
    ID NUMBER(8) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    ESCALA_ID NUMBER(8) NOT NULL,
    NOME VARCHAR(125) NOT NULL,
    CONSTRAINT ESCALA_TIPO_PK PRIMARY KEY (ID),
    CONSTRAINT FK_ESCALA_TIPO FOREIGN KEY(ESCALA_ID) REFERENCES TB_ESCALA(ID)
);
