ALTER TABLE TB_FUNCIONARIO RENAME COLUMN CARGO_FUNCIONARIO_ID TO CARGO_ID;
ALTER TABLE TB_FUNCIONARIO RENAME COLUMN EQUIPE_FUNCIONARIO_ID TO EQUIPE_ID;
ALTER TABLE TB_FUNCIONARIO RENAME COLUMN ESCALA_TRABALHO_ID TO ESCALA_ID;