CREATE TABLE TB_ESCALA_FUNCIONARIO (
    ESCALA_ID NUMBER(8) NOT NULL,
    FUNCIONARIO_ID NUMBER(8) NOT NULL,
    CONSTRAINT ESCALA_FK
        FOREIGN KEY(ESCALA_ID)
        REFERENCES TB_ESCALA(ID),
    CONSTRAINT FUNCIONARIO_FK
        FOREIGN KEY(FUNCIONARIO_ID)
        REFERENCES TB_FUNCIONARIO(ID),
    CONSTRAINT ESCALA_FUNCIONARIO_PK
        PRIMARY KEY(ESCALA_ID, FUNCIONARIO_ID)
);
