CREATE TABLE TB_PERFIL (
    ID NUMBER(8) GENERATED ALWAYS as IDENTITY(START WITH 1 INCREMENT BY 1),
    NOME VARCHAR2(35) NOT NULL,
    CONSTRAINT PERFIL_PK PRIMARY KEY (ID),
    CONSTRAINT NOME_UK UNIQUE KEY (NOME)
);