CREATE TABLE TB_AUTORIZACAO (
    ID NUMBER(8) GENERATED ALWAYS as IDENTITY(START WITH 1 INCREMENT BY 1),
    NOME VARCHAR2(35) NOT NULL,
    CONSTRAINT AUTORIZACAO_PK PRIMARY KEY (ID),
    CONSTRAINT AUTORIZACAO_NOME_UK UNIQUE (NOME)
);