CREATE TABLE TB_PERFIL_USUARIO (
    PERFIL_ID NUMBER(8) NOT NULL,
    USUARIO_ID NUMBER(8) NOT NULL,
    CONSTRAINT TB_PERFIL_USUARIO_PERFIL_FK
        FOREIGN KEY(PERFIL_ID)
        REFERENCES TB_PERFIL(ID),
    CONSTRAINT TB_PERFIL_USUARIO_USUARIO_FK
        FOREIGN KEY(USUARIO_ID)
        REFERENCES TB_USUARIO(ID),
    CONSTRAINT PERFIL_USUARIO_PK
        PRIMARY KEY(PERFIL_ID, USUARIO_ID)
);