CREATE TABLE TB_AUTORIZACAO_PERFIL (
    AUTORIZACAO_ID NUMBER(8) NOT NULL,
    PERFIL_ID NUMBER(8) NOT NULL,
    CONSTRAINT TB_AUTORIZACAO_PERFIL_AUTORIZACAO_FK
        FOREIGN KEY(AUTORIZACAO_ID)
        REFERENCES TB_AUTORIZACAO(ID),
    CONSTRAINT TB_AUTORIZACAO_PERFIL_PERFIL_FK
        FOREIGN KEY(PERFIL_ID)
        REFERENCES TB_PERFIL(ID),
    CONSTRAINT AUTORIZACAO_PERFIL_PK
        PRIMARY KEY(AUTORIZACAO_ID, PERFIL_ID)
);