DELETE FROM TB_AUTORIZACAO_PERFIL
WHERE AUTORIZACAO_ID = (SELECT ID FROM TB_AUTORIZACAO WHERE NOME = 'ROLE_PERFIL')
AND PERFIL_ID = (SELECT ID FROM TB_PERFIL WHERE NOME = 'USER');

DELETE FROM TB_AUTORIZACAO_PERFIL
WHERE AUTORIZACAO_ID = (SELECT ID FROM TB_AUTORIZACAO WHERE NOME = 'ROLE_PERFIL')
AND PERFIL_ID = (SELECT ID FROM TB_PERFIL WHERE NOME = 'EDITOR');

DELETE FROM TB_AUTORIZACAO_PERFIL
WHERE AUTORIZACAO_ID = (SELECT ID FROM TB_AUTORIZACAO WHERE NOME = 'ROLE_ESCALA_LISTAR_TIPOS');

DELETE FROM TB_AUTORIZACAO
WHERE NOME = 'ROLE_ESCALA_LISTAR_TIPOS';

INSERT INTO TB_AUTORIZACAO_PERFIL(AUTORIZACAO_ID, PERFIL_ID)
SELECT a.ID, p.ID
FROM TB_AUTORIZACAO a, TB_PERFIL p
WHERE p.NOME = 'EDITOR'
AND a.NOME IN ('ROLE_FUNCIONARIO_LISTAR',
            'ROLE_CARGO_LISTAR',
            'ROLE_EQUIPE_LISTAR',
            'ROLE_ESCALA_LISTAR',
            'ROLE_TURNO_LISTAR',
            'ROLE_FERIADO_LISTAR');