-- Inserir a Autorização ROLE_SUPORTE para os perfis EDITOR e ADMIN.
INSERT INTO TB_AUTORIZACAO(NOME) VALUES('ROLE_SUPORTE');

INSERT INTO TB_AUTORIZACAO_PERFIL(AUTORIZACAO_ID, PERFIL_ID)
SELECT a.ID, p.ID
FROM TB_AUTORIZACAO a, TB_PERFIL p
WHERE p.NOME = 'EDITOR'
AND a.NOME = 'ROLE_SUPORTE';

INSERT INTO TB_AUTORIZACAO_PERFIL(AUTORIZACAO_ID, PERFIL_ID)
SELECT a.ID, p.ID
FROM TB_AUTORIZACAO a, TB_PERFIL p
WHERE p.NOME = 'ADMIN'
AND a.NOME = 'ROLE_SUPORTE';