CREATE TABLE TB_DASHBOARD(
   ID NUMBER(8) GENERATED ALWAYS as IDENTITY(START WITH 1 INCREMENT BY 1),
   NOME VARCHAR2(125) NOT NULL UNIQUE,
   ESCALA_ID NUMBER(8) DEFAULT NULL,
   CONSTRAINT DASHBOARD_PK PRIMARY KEY (ID),
   CONSTRAINT FK_ESCALA FOREIGN KEY(ESCALA_ID) REFERENCES TB_ESCALA(ID)
);
