CREATE TABLE TB_SUPORTE (
    ID NUMBER(8) GENERATED ALWAYS as IDENTITY(START WITH 1 INCREMENT BY 1),
    RE VARCHAR2(8) NOT NULL,
    EMAIL VARCHAR2(250) NOT NULL,
    SOLICITACAO VARCHAR2(25) NOT NULL,
    CONSTRAINT SUPORTE_PK PRIMARY KEY (ID)
);