CREATE TABLE TB_SUPORTE (
    ID NUMBER(8) GENERATED ALWAYS as IDENTITY(START WITH 1 INCREMENT BY 1),
    RE NUMBER(6) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL,
    SOLICITACAO VARCHAR2(25) NOT NULL,
    CONSTRAINT SUPORTE_PK PRIMARY KEY (ID)
);